### ISSUE TITLE
I dont get 1.4ma

### ISSUE THREAD

**Issue by SaitamaTechno** [ghubcoder/micropython-pico-deepsleep#12]
I use picosleep and I get 6.6ma. It 3x reduced the power usage but it is not like 1.4ma.
Here is my code:

import picosleep

f=open("deepsleep.txt","w")
f.write("no")
f.close()

picosleep.seconds(2592000) # 1 month

**Comment by isnisn** [comment]
Maybe you have other stuff running besides the rp2040?

**Comment by SaitamaTechno** [comment]
Yes I have a wired gyro sensor and a touch screen but I dont send them any data or receive, Why is this consumption so high? Is it normal?

**Comment by elschopi** [comment]
even if not sending or receiving data, your peripherals will consume standby current, just like the pico. some chips (e.g. BME280 temperature sensing IC's) can be put into a standby mode via software command, maybe you can reduce the standby consumption of your peripherals that way.
the 1.4 mA is just for the pico with nothing else attached.

**Comment by SaitamaTechno** [comment]
@elschopi I got it thank you!
