### ISSUE TITLE
Contribute back to MicroPython

### ISSUE THREAD

**Issue by AndrewBoothman** [ghubcoder/micropython-pico-deepsleep#3]
Hello,

I've been trying to reduce the power usage on my Pico and this looks to be exactly what I'm looking for.

Have you considered getting your change upstreamed back into the main MicroPython rp2 port as a replacement for the existing `machine.deepsleep`? I think it would be a good fit for others who also want to reduce their power consumption.

I'd be willing to help but I know little python and even less C, so not sure how much I could contribute.

Thanks!

**Comment by ghubcoder** [comment]
Someone has done the hard work now and got this merged into Micropython with [this](https://github.com/micropython/micropython/pull/8832) commit. I will close this issue 🙂
